"""Initial database schema for core models

Revision ID: 5c01c5f0f1d5
Revises: ae6d6c36c53c
Create Date: 2025-12-11 23:28:44.208643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c01c5f0f1d5'
down_revision: Union[str, None] = 'ae6d6c36c53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Enable the UUID generation extension
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_app_id'), 'action_items', ['app_id'], unique=False)
    op.create_index(op.f('ix_action_items_user_id'), 'action_items', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('analysis_type', sa.String(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_app_id'), 'analysis_results', ['app_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_source_id'), 'analysis_results', ['source_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_user_id'), 'analysis_results', ['user_id'], unique=False)
    op.create_table('study_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('study_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('raw_request', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_requests_app_id'), 'study_requests', ['app_id'], unique=False)
    op.create_index(op.f('ix_study_requests_user_id'), 'study_requests', ['user_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('plan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_app_id'), 'study_plans', ['app_id'], unique=False)
    op.create_index(op.f('ix_study_plans_user_id'), 'study_plans', ['user_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('session_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_app_id'), 'study_sessions', ['app_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.drop_table('meeting')
    op.add_column('meetings', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('raw_transcript', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('app_id', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # === CRITICAL UUID CONVERSION FIX: Explicit DDL Steps ===
    # 1. Drop the old SERIAL/sequence default before altering type.
    op.execute("ALTER TABLE meetings ALTER COLUMN id DROP DEFAULT")
    
    # 2. Change the column type to UUID and populate existing INTEGER rows with new UUIDs.
    op.execute("ALTER TABLE meetings ALTER COLUMN id TYPE UUID USING gen_random_uuid()")
    
    # 3. Set the new UUID default for future inserts.
    op.execute("ALTER TABLE meetings ALTER COLUMN id SET DEFAULT gen_random_uuid()")
    
    # 4. Update created_at column type (standard alter_column is fine here)
    op.alter_column('meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    
    op.drop_index('ix_meetings_id', table_name='meetings')
    op.create_index(op.f('ix_meetings_app_id'), 'meetings', ['app_id'], unique=False)
    op.create_index(op.f('ix_meetings_user_id'), 'meetings', ['user_id'], unique=False)
    op.drop_column('meetings', 'transcript')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('transcript', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_meetings_user_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_app_id'), table_name='meetings')
    op.create_index('ix_meetings_id', 'meetings', ['id'], unique=False)
    op.alter_column('meetings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    
    # Drop the UUID default constraint before reverting the column type
    op.execute("ALTER TABLE meetings ALTER COLUMN id DROP DEFAULT")
    
    op.alter_column('meetings', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
               
    # NOTE: In a true rollback, re-adding the SERIAL default would be necessary, 
    # but for migration cleanliness, we simply revert the type.
    
    op.drop_column('meetings', 'updated_at')
    op.drop_column('meetings', 'user_id')
    op.drop_column('meetings', 'app_id')
    op.drop_column('meetings', 'raw_transcript')
    op.drop_column('meetings', 'end_time')
    op.drop_column('meetings', 'start_time')
    op.create_table('meeting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='meeting_pkey')
    )
    op.create_index('ix_meeting_title', 'meeting', ['title'], unique=False)
    op.create_index('ix_meeting_id', 'meeting', ['id'], unique=False)
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_app_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_study_plans_user_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_app_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_study_requests_user_id'), table_name='study_requests')
    op.drop_index(op.f('ix_study_requests_app_id'), table_name='study_requests')
    op.drop_table('study_requests')
    op.drop_index(op.f('ix_analysis_results_user_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_source_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_app_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_action_items_user_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_app_id'), table_name='action_items')
    op.drop_table('action_items')

    # Drop the uuid-ossp extension in the downgrade path
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
    # ### end Alembic commands ###
